# DataKwaliteit pipeline: laag `brons_p`, schema `demo_dataset`

## Laad packages

In [45]:
# %pip install nbformat
# %pip install numpy
# %pip install geopandas
# %pip install pandas
# %pip install re

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement re (from versions: none)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for re

In [1]:
import nbformat
import duckdb
from datetime import datetime
import os

#pandas en geopandas voor betere visualisatie bij testen of dingen werken.
import numpy
import geopandas as gpd
import pandas as pd

## Start DuckLake

In [2]:
%run ./start_ducklake.ipynb

09:48:21	DuckLake wordt geladen
09:48:21	DuckLake is succesvol geladen
09:48:21	De Spatial extensie wordt geladen
09:48:22	De Spatial extensie is succesvol geladen

## Laad data

In [40]:
%run ./laad_data.ipynb

10:22:56	Catalogi zijn aangemaakt
10:22:56	Schema's zijn aangemaakt
10:22:56	Tabellen zijn aangemaakt
10:22:56	Data zijn in de tabellen geladen

## Import datakwaliteit User Defined Functions (UDF's)

In [33]:
%run ./datakwaliteit_udf.ipynb

Er zijn 8 User Defined functions geladen
Couldn't find program: 'true'
Er zijn 7 testen toegevoegd vanuit de datakwaliteitsdimensies

## Tabel `nederland`

### Kolom `gemeente_website`

In [23]:
# kolomwaarde is niet leeg
dq01_kolomwaarde_is_niet_leeg(
    laag_1 = 'brons_p', 
    schema_1 = 'demo_dataset', 
    tabel_1 = 'nederland', 
    sleutelkolom_1 = 'id',
    kolom_1 = 'gemeente_website'    #datatype agnostisch
    )

### Kolom `aantal_1`

In [24]:
# kolomwaarde is tussen
dq02_kolomwaarde_is_tussen(
    laag_1 = 'brons_p', 
    schema_1 = 'demo_dataset', 
    tabel_1 = 'nederland', 
    sleutelkolom_1 = 'id',
    kolom_1 = 'aantal_1',  #datatype = getal
    kleiner_dan = 100,
    groter_dan = 5
    )

### Kolom `gemeente_email`

In [25]:
dq03_kolomwaarde_heeft_patroon(
    laag_1 = 'brons_p', 
    schema_1 = 'demo_dataset', 
    tabel_1 = 'nederland', 
    sleutelkolom_1 = 'id',
    kolom_1 = 'gemeente_email', #datatype = tekst
    patroon = r"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$" #email
    )

### Kolom `gemeente_naam`

In [26]:
# kolomwaarde begint niet met
dq04_kolomwaarde_begint_niet_met(
    laag_1 = 'brons_p', 
    schema_1 = 'demo_dataset', 
    tabel_1 = 'nederland', 
    sleutelkolom_1 = 'id',
    kolom_1 = 'gemeente_naam', #datatype = tekst
    patroon = "^[.]|^[ ]" #begint met spatie of punt
    )

### Kolom `beschrijving`

In [27]:
# kolomwaarde eindigt niet op
dq05_kolomwaarde_eindigt_niet_op(
    laag_1 = 'brons_p', 
    schema_1 = 'demo_dataset', 
    tabel_1 = 'nederland', 
    sleutelkolom_1 = 'id',
    kolom_1 = 'beschrijving', #datatype = tekst
    patroon = "[?]$|[.]$" #eindigd op vraagteken of punt
    )

# kolomwaarde heeft lengte
dq06_kolomwaarde_heeft_lengte(
    laag_1 = 'brons_p', 
    schema_1 = 'demo_dataset', 
    tabel_1 = 'nederland', 
    sleutelkolom_1 = 'id',
    kolom_1 = 'beschrijving',  #datatype = tekst
    korter_dan = 50,
    langer_dan = 10
    )

### Kolom `gemeente_naam`

In [28]:
# kolomwaarde zit niet in lijst
dq07_kolomwaarde_niet_in_lijst(
    laag_1 = 'brons_p', 
    schema_1 = 'demo_dataset', 
    tabel_1 = 'nederland', 
    sleutelkolom_1 = 'id',
    kolom_1 = 'gemeente_naam',  #datatype = tekst
    laag_2 = 'brons_p', 
    schema_2 = 'referentiedata', #lijst met gemeenten
    tabel_2 = 'gemeente_lijst', 
    kolom_2 = 'gemeente_naam',  #datatype = tekst
    )

### Kolom `lege_kolom`

In [29]:
# kolom is niet leeg
dq08_kolom_is_niet_leeg(
    laag_1 = 'brons_p', 
    schema_1 = 'demo_dataset', 
    tabel_1 = 'nederland', 
    kolom_1 = 'lege_kolom',  #datatype = tekst
    )

# Testen van datakwaliteitsdimensies

## kolomwaarde is niet uniek

In [19]:
D1TA_waarde_is_niet_uniek(
laag = 'brons_p',
schema = 'demo_dataset',
tabel ='nederland',
kolom = 'id',
sleutelkolom = 'id'
)

## Kolomwaarde van datatype float moet mogelijk datatype int zijn

In [10]:
D2TA1_float_mogelijk_int(
    laag_1= 'brons_p',
    schema_1 = 'demo_dataset',
    tabel_1 ='nederland',
    kolom_1 = 'float_zonder_float',
    sleutelkolom_1 = 'id'
)

## Kolomwaarde van datatype int moet mogelijk datatype bool zijn

In [16]:
D2TA2_int_mogelijk_bool(
    laag_1= 'brons_p',
    schema_1 = 'demo_dataset',
    tabel_1 ='nederland',
    kolom_1 = 'int_is_bool',
    sleutelkolom_1 = 'id'
)

## Kolomwaarde van datatype string moet mogelijk numeriek zijn

In [26]:
D2TB1_tekst_mogelijk_num(
    laag_1= 'brons_p',
    schema_1 = 'demo_dataset',
    tabel_1 ='nederland',
    kolom_1 = 'str_is_num',
    sleutelkolom_1 = 'id'
)

## Kolomwaarde van datatype string moet mogelijk boolean zijn

In [32]:
D2TB2_tekst_mogelijk_bool(
    laag_1= 'brons_p',
    schema_1 = 'demo_dataset',
    tabel_1 ='nederland',
    kolom_1 = 'str_is_bool',
    sleutelkolom_1 = 'id'
)

## Kolomwaarde van datatype string moet mogelijk datum zijn

In [75]:
#TODO werkt nog niet. Vereist uitgebreide regex statement
D2TB3_tekst_mogelijk_datum(
    laag_1= 'brons_p',
    schema_1 = 'demo_dataset',
    tabel_1 ='nederland',
    kolom_1 = 'str_is_datum',
    sleutelkolom_1 = 'id'
)

## Kolomwaarde tekstkolom bevat grootheid en eenheid combinatie

In [41]:
D2TC_tekst_is_grootheid_en_eenheid(
    laag_1= 'brons_p',
    schema_1 = 'demo_dataset',
    tabel_1 ='nederland',
    kolom_1 = 'grootheid_eenheid',
    sleutelkolom_1 = 'id'
)

# Kijk naar data

## Selecteer een DataSet tabel

In [42]:
#con.sql("DESC brons_p.dataset.nederland;").show()
con.sql("SELECT * FROM brons_p.demo_dataset.nederland;").fetchdf()

,id,provincie_naam,provincie_code,gemeente_naam,gemeente_code,gemeente_email,gemeente_website,aantal_1,aantal_2,datum_begin,datum_einde,beschrijving,lege_kolom,float_zonder_float,int_is_bool,str_is_num,str_is_bool,str_is_datum,grootheid_eenheid,grootheid_eenheid_d2tC
0,1,Gelderland,PV25,Arnhem,0202,info@arnhem.nl,https://www.arnhem.nl,50,100,2026-01-01,2020-12-01,<p>bla bla</p>,None,1.0,1,1.0,niet waar,1/2/26,1cm,False
1,2,Drenthe,PV22,Assen,GM0106,info@assen.nl,NaN,20,80,2020-03-15,2026-10-01,Lorem Ipsum is simply dummy text of the printi...,None,1.0,0,1,1,2026/05/01,1 cm,False
2,3,Zuid-Holland,PV28,Den Haag,GM0518,info@@denhaag.nl,https://www.denhaag.nl,10,30,1989-10-01,2020-01-01,making it look like readable English. Many des...,None,1.0,1,str,iets anders,01052026,50%,False
3,4,Groningen,PV20,Groningen,GM0014,info@groningen.nl,https://www.groningen.nl,1000,1001,1970-11-30,2023-03-15,Where can I get some?,None,1.0,0,10e10,j,kaas,10°C,False
4,5,Overijssel,PV23,Zwolle,GM0193,info@zwolle.nl,https://www.zwolle.nl,3,15,2020-03-15,2020-03-15,200,None,1.0,1,4e-10,True,26-01-30,5h,False
5,4,Groningen,PV20,Groningen,GM0014,info@groningen.nl,https://www.groningen.nl,1000,750,1970-11-30,2023-03-15,Where can I get some?,None,1.0,2,boo,F,2026/12/30,niet,True

## Selecteer een Referentie tabel

In [12]:
#con.sql("DESC brons_p.referentiedata.gemeente_lijst;").show()
con.sql("SELECT * FROM brons_p.referentiedata.gemeente_lijst;").fetchdf()

┌───────────────┬───────────────┐
│ gemeente_naam │ gemeente_code │
│    varchar    │    varchar    │
├───────────────┼───────────────┤
│ Arnhem        │ GM0202        │
│ Assen         │ GM0106        │
│ s-Gravenhage  │ GM0518        │
│ Zwolle        │ GM0193        │
│ Utrecht       │ GM0344        │
│ Groningen     │ GM0014        │
└───────────────┴───────────────┘

## Selecteer de DataKwaliteit Log tabel

In [28]:
#con.sql("DESC brons_p.datakwaliteit.log;").show()
con.sql("SELECT meetwaarde_false_1 FROM brons_p.datakwaliteit.log;").fetchdf()

    meetwaarde_false_1
0                    2
1                    1
2                    3
3                    1
4                    1
5                    3
6                    3
7                    2
8                    6
9                    0
10                   0
11                   0
12                   0
13                   2
14                   6
15                   5
16                   4

In [39]:
con.sql("DROP TABLE IF EXISTS brons_p.demo_dataset.nederland")